### ISSUE TITLE
Support for MaTouch_ESP32-C3 (ESP32C3SPI35)

### ISSUE THREAD

**Issue by phpbbireland** [DustinWatts/FreeTouchDeck#115]
Will the code work with Makerfabs-ESP32-C3-SPI-TFT-with-Touch boards?

Mike

**Comment by DustinWatts** [comment]
Hi @phpbbireland!

FreetouchDeck should work on any ESP32 that has WiFi and BLE. I haven't tested it. But you should be able to change the User_Setup.h for your screen and board. And also change some #defines in the main *.ino sketch. Let me know if it works out!

**Comment by phpbbireland** [comment]
Thanks, will try some more...

**Comment by DustinWatts** [comment]
This issue is still open... did you make any progress?

**Comment by phpbbireland** [comment]
Sorry, real busy, forgot to close this...
Haven't got a chance to test but the extra info should  suffice...

**Comment by DustinWatts** [comment]
You can always reopen this issue if you make some progress and show it to other interested in doing the same thing! 👍
