### ISSUE TITLE
Touchscreen not working on a ESP32-2432s028r

### ISSUE THREAD

**Issue by nikvs216** [DustinWatts/FreeTouchDeck#119]
Hi, i tried you a fork from your repository from Raycast7373 on my esp32-2432s028r, it successfully compiled but im stuck on the touch calibration with dont work, i tried to use user_setup.h of the library that came with my esp wich didnt work, i looked up at my pins and everything is connected right also ResistiveTouch is uncomment, anyone maybe know what it could be?

**Comment by DustinWatts** [comment]
HI Nikuś, if you used the fork by Raycast, you probably should post your question on that repo. I cannot answer questions regarding code I did not write. I have no idea what Raycast did to the original code.
