### ISSUE TITLE
Support for ESP32-2432S028

### ISSUE THREAD

**Issue by werwaswarum** [DustinWatts/FreeTouchDeck#120]
Hello,

I bought the ESP-32 2432S028 board from Aliexpress and modified  FreeTouchDeck in a way that it can run on that board.
Would it be of interest to merge the changes in to the main repo?
As this board use two SPI interfaces, I needed to add the library eTouch, would this be inline with the devolpment idea?

Best regards,
werwaswarum

**Comment by werwaswarum** [comment]
Sorry, I just saw that there is already a repo for this. Somehow I went overthis before

**Comment by DustinWatts** [comment]
No worries. Could you point me to that repo? If it is not too much work I might integrate it in to the original FreeTouchDeck repo. Maybe even just a different branch.

**Comment by werwaswarum** [comment]
Hi sure,
My Fork:  https://github.com/werwaswarum/FreeTouchDeck
And the eTouch library I used:  https://github.com/achillhasler/TFT_eTouch

My Idea was to introduce a statement similar to the one for the ESP32TouchDownS3.
Please let me know if I can support you.
