### ISSUE TITLE
Problem with ledcSetup while uploading FreeTouchDeck.ino

### ISSUE THREAD

**Issue by Toxic-Engineer** [DustinWatts/FreeTouchDeck#126]
Hey, 

I get an error in this section while uploading the .ino data. (I use the exact same hardware as in the Youtube video)

  ledcSetup(0, 5000, 8);
#ifdef TFT_BL
  ledcAttachPin(TFT_BL, 0);
#else
  ledcAttachPin(backlightPin, 0);
#endif // defined(TFT_BL)
  ledcWrite(0, ledBrightness); // Start @ initial Brightness

Error: 'ledcSetup' was not declared in this scope

TY in advance

**Comment by DustinWatts** [comment]
The quick solution is to downgrade the ESP32 Arduino core. Because there are some breaking changes regarding ledc in version 3. If you go for something like 2. something, It will work again. The long time solution is something I am working on but it can take some time due to being really busy...

**Comment by Toxic-Engineer** [comment]
Mate, you are a bloody legend. TY, I love my touchdeck!

**Comment by DustinWatts** [comment]
You are welcome mate! :)

It is just a temporary fix, but it does work. I'm keeping this Issue open, because I need to make FreeTouchDeck compatible with the newest version of the Arduino Core.

**Comment by Dark1886** [comment]
@DustinWatts This issue specifically mentioned an MQTT broker, but would it be possible to have the FreeTouchDeck just be an MQTT client that could execute some commands if it receives an MQTT message from an external broker?
