### ISSUE TITLE
KEY_MEDIA_NEXT_TRACK and KEY_MEDIA_PREVIOUS_TRACK not listed in index.htm

### ISSUE THREAD

**Issue by charliejgallo** [DustinWatts/FreeTouchDeck#24]
KEY_MEDIA_NEXT_TRACK and KEY_MEDIA_PREVIOUS_TRACK key values are present in Action.h but missing in the list of media keys in index.htm

**Comment by DustinWatts** [comment]
Well spotted! Thanks for reporting. I missed those. Assigned and will add them in the next release. In the mean time, you could add them yourself if you can't wait ;)

After:
```
{
   name: 'Stop',
   value: '5'
}
```
Add:
```
,
{
   name: 'Next',
   value: '6'
},
{
   name: 'Previous',
   value: '7'
}
```

Don't forget the `,`!

**Comment by DustinWatts** [comment]
https://github.com/DustinWatts/FreeTouchDeck/commit/1172fc323741a97b7452c1c4ed75422893d5e877 aka version 0.9.10 fixes this!
