### ISSUE TITLE
extended audio functionality

### ISSUE THREAD

**Issue by gufpewga** [DustinWatts/FreeTouchDeck#26]
Hi,
I really like this project. And wa thinking if it was posible to add some funcionality like on GOXLR to control audio. I mean that if you for example swipe left on main screen it takes you to diferent layout that will have sliders with different audio sources. It is just idea, don't know if it is doable. But would be cool to have 2 in 1 that doesnt take too much space on desk.

**Comment by DustinWatts** [comment]
Hi @gufpewga ! Unfortunately not all touch controller support gestures natively. That would mean some sort of software "hack" to make that possible. For now this is beyond the scope of FreeTouchDeck. But I agree that this would be a great feature!

**Comment by briight** [comment]
im already have a physical volume controller and im looking at intregrating it into/on my freetouchdeck   just waiting for parts 

this is the one i am using atm https://github.com/omriharel/deej

**Comment by briight** [comment]
i have posted some pics on the discord  look up briight
