### ISSUE TITLE
DEL key not defined

### ISSUE THREAD

**Issue by Zathras42** [DustinWatts/FreeTouchDeck#31]
Delete key is not defined.  Please add.

In action.h under _case 2: // Send TAB ARROW etc_
    case 10:
      bleKeyboard.write(KEY_DELETE);
      break;

In index.htm under _name: 'Arrows and TAB',_
   {
      name: 'Delete',
      value: '10'
   }

**Comment by DustinWatts** [comment]
Thanks! I forgot that while creating the keys :)

**Comment by DustinWatts** [comment]
https://github.com/DustinWatts/FreeTouchDeck/commit/1172fc323741a97b7452c1c4ed75422893d5e877 aka version 0.9.10 Fixes this!
