### ISSUE TITLE
Pcb

### ISSUE THREAD

**Issue by Rowdydangerous** [DustinWatts/FreeTouchDeck#34]
Where is a copy of the pcb file? I couldn't find it on pcbway or here on github.

**Comment by DustinWatts** [comment]
https://github.com/DustinWatts/ESP32_TFT_Combiner

Good issue, I should have put a link in the repository itself, I only did that on Instructables, Hackaday etc, but not here.

**Comment by Rowdydangerous** [comment]
Thank you
