### ISSUE TITLE
Question: Fusion360 case

### ISSUE THREAD

**Issue by PeterEIER** [DustinWatts/FreeTouchDeck#35]
Hi Dustin, it seems to me that the Fusion360 design is missing the back/stand of FreeTouchDeck case. When I import the f3z file in to Fusion360 I get 2 drawing, the front of the case and dummy ILI9488 TFT screen.

My question is this... would it be possible to also share the back/stand?

Thx.

**Comment by DustinWatts** [comment]
Hi Peter! The FreeTouchDeck Fusion360 file contains both the front and the back, each is in it's own component.
<img width="310" alt="Screen Shot 2021-02-22 at 13 33 21" src="https://user-images.githubusercontent.com/18088135/108709215-b1560d80-7512-11eb-834b-a59bc23f3bcf.png">

You can show/hide the ones you want by using the little eye to the left of each component.

**Comment by PeterEIER** [comment]
ouch, my wrong... you are completely right... sorry for bothering you!

FYI - I will make some changes to the original case to have 2 FreeTouchDecks in just 1 case ;-)

Thx, great project!

**Comment by DustinWatts** [comment]
@PeterEIER No problem, you are welcome! Looking forward to see your MultiTouchDeck! ;)
