### ISSUE TITLE
Numpad support

### ISSUE THREAD

**Issue by StevenCellist** [DustinWatts/FreeTouchDeck#36]
Hey Dustin,
It would be great if Numpad support could be added!
OBS for example has the possibility to distinguish between a normal `1` and `NUMPAD-1`.
Adding Numpad keys would reduce the pain of Windows being picky about F13+ :)

**Comment by DustinWatts** [comment]
@StevenCellist Great idea! This would require some investigation.

**Comment by DustinWatts** [comment]
https://github.com/DustinWatts/FreeTouchDeck/commit/faa9d31d738b3f14bbc285f9732b96536a5d19ab adds Numpad support. Make sure to also update https://github.com/DustinWatts/ESP32-BLE-Keyboard !
