### ISSUE TITLE
ILI9488 - MSP3520 with Touch not working?

### ISSUE THREAD

**Issue by schneika** [DustinWatts/FreeTouchDeck#41]
I have ordered the TFT with Touch from AliExpress. Version MSP3520. The TFT Display shows the Icons, but the Touch is not working. I dont know what Touch-Chip is the MSP3520 Version...

**Comment by DustinWatts** [comment]
@schneika Is the chip the XPT2046? The screen also come without touch, so you have to make sure they have the film on top with a silver boarder. Also U2 (the chip) should be populated. 

The first time FTD boots, it does a calibration. If that fails or does not calibrate o.k. and touch doesn't work, you can open the serial monitor (assuming you used the Arduino IDE), set the baud rate to 9600, and make sure you've selected "No line ending" and type `cal reset`, to calibrate again.

**Comment by schneika** [comment]
Yes, the Chip is the XPT2046. 
And thanks for your help.: After recalibration as suggested from you (via Serial Monitor - cal reset) - the Touch-Controller is working as expected. Fantastic work!

**Comment by DustinWatts** [comment]
@schneika Good to hear! :D
