### ISSUE TITLE
Missing keys (If you find them, report them here)

### ISSUE THREAD

**Issue by DustinWatts** [DustinWatts/FreeTouchDeck#45]
A list so far:

- ESC
- PrtScn
- Home
- End

**Comment by TheAlgorythm** [comment]
I would need ESC and custom text to interact with vim.

**Comment by DustinWatts** [comment]
> I would need ESC and custom text to interact with vim.

Can you explain a bit more about the custom text?

**Comment by TheAlgorythm** [comment]
Well, would it be possible to print some characters (like the length of a word) out. e.g. ":Buffer" or any other command. Another use-case for me (and maybe for others also?) would be to type common or hard to reach code out (like `\begin` in `LaTeX`).

**Comment by DustinWatts** [comment]
Yes that is possible. But it is not possible in the configurator. You would have to hard code that in FreeTouchDeck.ino. This is a future feature because indeed other people also would like this.

**Comment by DustinWatts** [comment]
https://github.com/DustinWatts/FreeTouchDeck/commit/faa9d31d738b3f14bbc285f9732b96536a5d19ab adds ESC, HOME, END, PrintSreen.

**Comment by danielo515** [comment]
Well, in the same spirit as @TheAlgorythm I also would love to be able to configure custom MACROS that are just send as keystrokes.
On top of that, i think that the entire list of characters needs to be included, at least all the characters that can be typed with a keyboard: `[]~@<>{}()=: ; _ ` are just some examples that I use daily

**Comment by DustinWatts** [comment]
@danielo515 As I said to TheAlgorythm, it is possible, only not through the configurator. You will have to edit the code and create custom macros. 

I do take notice of the characters and will add them as soon as possible.

**Comment by danielo515** [comment]
> @danielo515 As I said to TheAlgorythm, it is possible, only not through the configurator

Well, thanks for confirming it is possible on the code, but one of the things that attracted me to the touch-deck was being able to quickly iterate on macros, as opposed to my QMK macropads that require a compilation step.
So my vote is to find a way to do that on the GUI.

**Comment by DustinWatts** [comment]
@danielo515 https://github.com/DustinWatts/FreeTouchDeck/commit/3aa366427ff764bf857e26cfc1cbb0534e1efc70 adds the missing keys.

Also, a new file is there called UserActions.h. In here there are functions that you can create (userAction1(); etc) that will let you put the whole function under a button via the configurator. Have a look at the examples!

**Comment by danielo515** [comment]
That looks awesome @DustinWatts !!!
Thank you very much
