### ISSUE TITLE
The "Space" key doesn't seem to be an option in the configurator for commands

### ISSUE THREAD

**Issue by witnessmenow** [DustinWatts/FreeTouchDeck#5]
Doesn't seem like there is an option for the space bar in the current options in the configurator

**Comment by DustinWatts** [comment]
That is not by design... I overlooked that one. I'll add it to the next push.

**Comment by DustinWatts** [comment]
Commit https://github.com/DustinWatts/FreeTouchDeck/commit/6e6fffe14f2e160d4251ad7cb5852b543e2ead14 added the spacebar to the "letters" list in the configurator. Not sure if this is the best place.
