### ISSUE TITLE
Touch screen malfunctioning cal reset does not work. 

### ISSUE THREAD

**Issue by Lucero-delcielo** [DustinWatts/FreeTouchDeck#55]
I have been using my FTD for a few days now, and it has been working great, but today I tried to use it and the touch screen would work a little but seemed to be making its own touches. I ran cal reset a couple times, but it seemed to just touch each corner on its own without me touching it at all. I am at a loss. Thoughts?

**Comment by DustinWatts** [comment]
Hi @Lucero-delcielo, my first guess is a bad connection to the touch controller. Are you using a breadboard? Or the combiner PCB? Or a prototype board? Anyway, I would check the T_DO, T_CS, and T_CLK for a bad connection or a short. Maybe even reflow the pins if you are using the combiner board or a prototype board.

**Comment by Lucero-delcielo** [comment]
Thank you for the advice Dustin. It seems my soldering was a bit shoddy on those pins. Reflowing them solved the issue. Thanks so much for your help!

**Comment by DustinWatts** [comment]
Good to hear! :D
