### ISSUE TITLE
Wifi on by default - Control of local Shelly devices

### ISSUE THREAD

**Issue by danielhunt** [DustinWatts/FreeTouchDeck#60]
@DustinWatts one of the use cases of my ESP32 TouchDown will be to control a few Shelly devices in my home - these are all controlled over wifi using a simple HTTP API.

To do this I will be changing FreeTouchDeck in ways you may not like to see it go (for example: Wifi on by default, wifi on at all times, Major UI modifications to allow for colour-selection for some RGB lights, ...etc)

Would you like me to contribute PRs here in this vein, or would it be taking FreeTouchDeck in a direction you would rather not see it go? I am happy to go alone on this, but equally happy to contribute what I can too.

**Comment by DustinWatts** [comment]
I think if that works it would be great to see. The reason I have BT stopped and WiFi started when entering the configurator is that is was taking up too many resources and didn't play nice. But with the modified code from #51 this might be handled better without crashes.

**Comment by danielhunt** [comment]
Ah - excellent! Well I already have a version working that connects to Wifi on demand and triggers a set of Rest HTTP calls to some of my Shelly devices.
So I'm happy that it's **possible** at least 😄 

I'll close this issue so, and create PRs in the future when it starts taking shape 👍
