### ISSUE TITLE
remove jquery-3.5.1.slim.min.js and use cloudflare version. (save space)

### ISSUE THREAD

**Issue by gjelsoe** [DustinWatts/FreeTouchDeck#61]
Would it not be a good idea to use Cloudflare JQuery in index.htm and save 73kb of space ?

It's a simple fix by replacing <script src="jquery-3.5.1.slim.min.js"></script>
with <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>

It will also make it easier to upgrade to newer version without thinking about space usage..

**Comment by DustinWatts** [comment]
I chose to include the jQuery build in the data folder, because for the configurator to function it would require internet access. If you start the configurator in AP mode or do not want your ESP32 to connect to the internet the configurator would not work.
