### ISSUE TITLE
File names are corrupted

### ISSUE THREAD

**Issue by abrilevskiy** [DustinWatts/FreeTouchDeck#73]
![image](https://user-images.githubusercontent.com/7629383/137363621-048d915c-cf73-478d-a74d-57787d20b579.png)

**Comment by DustinWatts** [comment]
Hi @abrilevskiy, this is happening more often when using the latest ESP32 Arduino Core. I'm looking in to how this happens. So solve it immediately, you can compile the code to version 1.0.6 of the ESP32 Core. If you do not upload the data folder, the files are untouched and you are ok.
