### ISSUE TITLE
Add a checkbox to press all the buttons instead of one after the other

### ISSUE THREAD

**Issue by danielo515** [DustinWatts/FreeTouchDeck#77]
Hello.
I just started using my free-touch-deck and I almost immediatly noticed that I can not execute complex combos.
For example `alt + gui + ctrl + ]`. I tried selecting `alt + gui + ctrl` on the first action and then a similar simbol on second action, but they are executed one after the other. I would love to be able to make them be pressed at the same time.

Regards

**Comment by DustinWatts** [comment]
Hi @danielo515, if you select `alt+gui+crtl` from the combo's menu, then a symbol on action 2, it should press all of them before releasing. Keys are releases at the end of the three actions. Or if you select release all... I will check if I can replicate your problem...

**Comment by DustinWatts** [comment]
> For example `alt + gui + ctrl + ]`. I tried selecting `alt + gui + ctrl` on the first action and then a similar simbol on second action, but they are executed one after the other.

I just confirmed that this configuration presses `alt+gui+crt+]` and then releases them all:
<img width="419" alt="Screen Shot" src="https://user-images.githubusercontent.com/18088135/141420818-b44e5abe-9e2c-4e2b-8f20-599fa815953b.png">

**Comment by danielo515** [comment]
Oh, that is awesome.
Have you added that symbol to the next release already? Wonderful.
Sorry, by reading the docst I thought it was like I described. Glad to see it is not.

**Comment by DustinWatts** [comment]
> Oh, that is awesome. Have you added that symbol to the next release already? Wonderful. Sorry, by reading the docst I thought it was like I described. Glad to see it is not.

No problem!
