### ISSUE TITLE
SPIFFS is deprecated

### ISSUE THREAD

**Issue by danielo515** [DustinWatts/FreeTouchDeck#79]
When I try to compile the project I get a warning telling me that SPIFFS is deprecated, and that I should consider moving to other filesystem like LittleFS.

Just pointing it out

**Comment by DustinWatts** [comment]
Hi @danielo515 Correct, LittleFS is the next thing on my list. It should not be hard to do, but I want to test it thoroughly.

**Comment by DustinWatts** [comment]
Check cc944c40cbb3aa55c41793ae6136d601e770a944 This adds the ability to use LitteFS instead of SPIFFS.
