### ISSUE TITLE
Display version number somewhere

### ISSUE THREAD

**Issue by witnessmenow** [DustinWatts/FreeTouchDeck#8]
Would be good to have a code version number displayed somewhere so people could mention what version they are on in issues

**Comment by DustinWatts** [comment]
It displays it during boot in the top left corner. But after there is no way as of yet. I am planning the one still unused button in the "Settings" menu an "Info" button. Displaying all kinds of information like version, BLE Name/MAC, battery voltage (if a battery is used) and some other stuff. If you have other ideas what can be on that page, let me know!

**Comment by DustinWatts** [comment]
Commit https://github.com/DustinWatts/FreeTouchDeck/commit/6e6fffe14f2e160d4251ad7cb5852b543e2ead14 added an info screen to the settings menu. Displaying the FreeTouchDeck version and some other useful information.
