### ISSUE TITLE
ESP32 TouchDown Case?

### ISSUE THREAD

**Issue by danielo515** [DustinWatts/FreeTouchDeck#80]
Hello.
I just printed the top part of the case just to realise that my ESP32 TouchDown does not fit. And even if it did, there is not enough room to put the USB cable. Is the case even compatible with the TouchDown? If not, It will be nice to note that ont he readme to save some users frustation

**Comment by DustinWatts** [comment]
Hi @danielo515 The case for the ESP32 TouchDown is slightly different. You should print the case from the ESP32 TouchDown page: https://github.com/DustinWatts/ESP32-TouchDown But good idea, I will edit the README.md to point users to this fact!

**Comment by danielo515** [comment]
Thank you, now I have the correct one printed

**Comment by DustinWatts** [comment]
Good to hear!
