### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by eismeraldo** [DustinWatts/FreeTouchDeck#81]
First of all, thank you very much for the FreeTouchDeck library, it's wonderful.
I downloaded the latest libraries as you explained here: https://www.instructables.com/A-Bluetooth-ESP32-TFT-Touch-Macro-Keypad/
The compiler then displayed an error. The name KEY_NUM_ASTERISK is in file Action.h in line 533 and according to ESP32-BLE-Keyboard-master / BleKeyboard.h line 33 it should probably be KEY_NUM_ASTERIX. After the change everything compiled without errors.

**Comment by TheAleSch** [comment]
Thank you! =D

**Comment by DustinWatts** [comment]
I fixed the fork with the correct spelling! :)
