### ISSUE TITLE
[FEATURE REQUEST] Deej compatibility

### ISSUE THREAD

**Issue by kingpin1905** [DustinWatts/FreeTouchDeck#82]
Add a Deej page/option

(From the deej github):
> Deej is an open-source hardware volume mixer for Windows and Linux PCs. It lets you use real-life sliders (like a DJ!) to seamlessly control the volumes of different apps (such as your music player, the game you're playing and your voice chat session) without having to stop what you're doing.

https://github.com/omriharel/deej

**Comment by briight** [comment]
iv had it working on both branches 

i think u have to add    BluetoothSerial SerialBT;     at the top but its been a long itme since i did it

**Comment by DustinWatts** [comment]
What exactly do you mean by "Deej compatibility"?

**Comment by kingpin1905** [comment]
> What exactly do you mean by "Deej compatibility"?

Add a page on the FreeTouchDeck and make the Arduino communicate with the Deej.exe (Arduino sends messages to the serial monitor and is picked up by the Deej.exe software)
