### ISSUE TITLE
KEY_NUM_ASTERISK should be KEY_NUM_ASTERIX in Action.h

### ISSUE THREAD

**Issue by Humancell** [DustinWatts/FreeTouchDeck#83]
Incredible project and PCBs!  I've just built my first FreeTouchDecks, and they are working great!  After one small change ...

I downloaded everything following your YouTube instructions, and when I went to build I got an error that KEY_NUM_ASTERISK was not defined in scope.  I took a look at BleKeyboard.h and found that the spelling was different: KEY_NUM_ASTERIX

I edited the following line: https://github.com/DustinWatts/FreeTouchDeck/blob/master/Action.h#L533

With that small change everything built, uploaded, and is working!

Thank you for the great project!

**Comment by DustinWatts** [comment]
I updated the BLE Keyboard fork. Let's keep correct spelling where ever possible! :)
