### ISSUE TITLE
Add restart button to Wifi screen

### ISSUE THREAD

**Issue by ZainKergaye** [DustinWatts/FreeTouchDeck#89]
I think that there should be a restart button on your wifi screen just so that if it doesn't get configured correctly you don't have to manually pull the plug

**Comment by DustinWatts** [comment]
Good idea!

**Comment by DustinWatts** [comment]
Btw... FreeTouchDeck will always start and AP if it can't connect to your WiFi so you can always get to it, by connecting to the default AP.

**Comment by Not-InstaGraham** [comment]
> Btw... FreeTouchDeck will always start and AP if it can't connect to your WiFi so you can always get to it, by connecting to the default AP. So maybe we leave the button out, because it always starts the webserver?

Seems like this would be a handy edition simply because of the sheer variety of setup variants users could have. Ensures a quick way to refresh the ESP without having to connect to the AP every time (assuming you’re having issues with the wifi).

**Comment by DustinWatts** [comment]
Let's see if this works for everyone 😄 

Off course this is not in the release yet. So only manually compiling and uploading is needed.

**Comment by DustinWatts** [comment]
No complains a of now. So closing. Feel free to reopen!
