### ISSUE TITLE
Allow batch upload for icons

### ISSUE THREAD

**Issue by Not-InstaGraham** [DustinWatts/FreeTouchDeck#90]
Figured this would be helpful for testing/initial setup when a user might have to reformat the ESP and start from the beginning. Or if somebody would rather just upload all their icons in a single step rather than machine gun them through the web app.

**Comment by DustinWatts** [comment]
The AsyncWebserver I am using on the ESP32, should be able to handle multiple file uploads at once. Maybe it is a simple as changing this line in the index.html:

_929_:`<input form="uploadfile" type="file" name="name" accept=".bmp"><br /><br />`

to

_929:_`<input form="uploadfile" type="file" name="name" accept=".bmp" multiple><br /><br />`

I will try as soon as I have time. If someone else wants to test... feel free! 😄

**Comment by DustinWatts** [comment]
Let's see if this works for everyone 😄 

Off course this is not in the release yet. So only manually compiling and uploading is needed.

**Comment by DustinWatts** [comment]
Well, it works for me so I'm closing this for now. Feel free to re-open if there are any issues.
