### ISSUE TITLE
Add "Run Application" Action

### ISSUE THREAD

**Issue by ZornTaov** [DustinWatts/FreeTouchDeck#91]
I notice you're already using "Action 2" to start the calculator for windows using Win+R, it would be nice if the Configurator had this option with a textbox prompt for what application to run.

**Comment by DustinWatts** [comment]
Adding strings to type is a possible future update. For now you can use the FreeTouchDeck Helper application: https://github.com/DustinWatts/FreeTouchDeck-Helper
