### ISSUE TITLE
Management of automated blinds

### ISSUE THREAD

**Issue by NigaMan** [DustinWatts/FreeTouchDeck#93]
And what if you add mqtt broker so that you can manage automated blinds?

**Comment by DustinWatts** [comment]
There not enough RAM, so BLE, the TFT and WiFi can not be used at the same time. With a next version of the ESP32 TouchDown this might be possible. But not with this version of FreeTouchDeck.

**Comment by Dark1886** [comment]
@DustinWatts This issue specifically mentioned an MQTT broker, but would it be possible to have the FreeTouchDeck just be an MQTT client that could execute some commands if it receives an MQTT message from an external broker?

**Comment by DustinWatts** [comment]
It can be. But that would mean a really big re-write. I hope that in version 2.0. I can be either or even better, both. Especially when using the ESP32 S3 which is very powerful. I'm also thinking of making a board with the H series and the S3 which means there is more room for home automation. But for now, it is a no.

**Comment by TobbeG** [comment]
@DustinWatts How are you doing now?
