### ISSUE TITLE
More buttons 

### ISSUE THREAD

**Issue by IdoP7** [DustinWatts/FreeTouchDeck#94]
Hello, 
Im trying to get in each menu 12 smaller buttons instead of 6 big.  Somewhere in the middle I get lost… tried few times from scratch without great success…
Someone tried it? Maybe can help? I dont mind to ditch the web server and set each button manually but I must have 12 button in each menu

**Comment by DustinWatts** [comment]
The development branch of this repo has the option for more buttons and menus. The only thing missing is the browser based configurator. So you will have to manually edit the JSON configuration.

**Comment by DustinWatts** [comment]
I'm hoping to have some time coming to make the devopment branch stable for release...
