### ISSUE TITLE
Support non BLE operations

### ISSUE THREAD

**Issue by realhagie** [DustinWatts/FreeTouchDeck#96]
feature request:

I like to use the FreeTouchDeck on my Desktop Computer without BT. 

One Option could be have the ESP act as HID , afaik not possible due to missing host mode on esp32 (prior to S3). 
Other option could be have a small Client/Server on the desktop which connects to FreeTouchDeck via network.

**Comment by DustinWatts** [comment]
You could use serial to communicate with a host device. But this requires some work. The best thing is to make it compatible with the S3, which I am working on now :D
