### ISSUE TITLE
Add support turn off display and additional timers for 1,2,5 minutes.

### ISSUE THREAD

**Issue by Satenex** [DustinWatts/FreeTouchDeck#99]
Now (0.9.17) there is only sleep mode. Is it possible to add a function to turn off the display (screen + backlight) and additional timers for 1,2,5 minutes?

**Comment by DustinWatts** [comment]
Good idea. 

I'm thinking:

1. Options for screen saver 
2. Option for sleep

Both with a separate timer. Kinda like you OS does. Should not be hard to implement.

**Comment by Satenex** [comment]
up
